# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "box-cutter/ubuntu1404-dektop"
  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "https://atlas.hashicorp.com/box-cutter/boxes/ubuntu1404-desktop/versions/2.0.5/providers/virtualbox.box"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
     vb.gui = true
     vb.name = "Synoptic"
     vb.memory = "1024"
    end
  # Provisioning done with shell commands for this VM    
    config.vm.provision "shell",inline: <<-SHELL

      # Install all the necessary packages required to make the tools rul
      sudo apt-get -y update
      sudo apt-get -y install openjdk-7-jre
      sudo apt-get -y install openjdk-7-jdk
      sudo apt-get -y install ant
      sudo apt-get -y install git
      sudo apt-get -y install graphviz
      #Adobe Flash player required in order to view the YouTube video
      sudo apt-get install flashplugin-installer
      #Software required to unzip the zip file downloaded from git
      sudo apt-get install unzip

      # Files and folders that have to reside on the desktop are downloaded from the vm-contents folder
      cd /home/vagrant/Desktop
      sudo wget https://raw.githubusercontent.com/SoftwareEngineeringToolDemos/FSE-2011-Synoptic/priya/synoptic-dev/build-vm/vm-contents/Installation.txt
      sudo wget https://raw.githubusercontent.com/SoftwareEngineeringToolDemos/FSE-2011-Synoptic/priya/synoptic-dev/build-vm/vm-contents/License.txt
      sudo wget https://raw.githubusercontent.com/SoftwareEngineeringToolDemos/FSE-2011-Synoptic/priya/synoptic-dev/build-vm/vm-contents/ReadMe.txt
     sudo wget https://raw.githubusercontent.com/SoftwareEngineeringToolDemos/FSE-2011-Synoptic/priya/synoptic-dev/build-vm/vm-contents/Synoptic-Summarizing%20Log%20Files-ToolDemo%20-%20YouTube%281%29.desktop 
     
      # Give full permission for all files on the desktop so that the user can access all of them
      sudo chmod 777 /home/vagrant/Desktop/DemoVideo.desktop
      sudo chmod 777 /home/vagrant/Desktop/Installation.txt
      sudo chmod 777 /home/vagrant/Desktop/License.txt
      sudo chmod 777 /home/vagrant/Desktop/ReadMe.txt

      # Download the master-folder as zip from the SoftwareEngineeringToolDemos/FSE-2011-Synoptic repo for the tool
      wget  https://github.com/SoftwareEngineeringToolDemos/FSE-2011-Synoptic/archive/master.zip
      unzip master.zip
      mv FSE-2011-Synoptic-master/ Synoptic
      
      # A subfolder of this Synoptic folder contains all the binaries. Make a copy of that on the Desktop into the Binaries folder
      cp -R Synoptic/bin /home/vagrant/Desktop/Binaries
      sudo chmod -R 777 /home/vagrant/Desktop/Binaries

      # Remove the zip folder after extracting the files and give full permission to the Synoptic folder in order to view output
      rm -rf master.zip
      sudo chmod -R 777 /home/vagrant/Desktop/Synoptic
      cd Synoptic
      
      #Build the synoptic project
      ant synoptic
      #Check build with usage screen
      ./synoptic.sh -h

      #In order to open the terminal on boot, place the .desktop file in the ~/.config folder
      cd /home/vagrant/.config
      mkdir autostart
      cd autostart
      touch gnome-terminal.desktop
      printf "[Desktop Entry]\n Type=Application\n Name=Terminal\n Exec=gnome-terminal \nNoDisplay=false" >> gnome-terminal.desktop

      # Make sure the terminal opens up at the correct location- "~/Desktop/Synoptic" for ease of user
      printf "cd /home/vagrant/Desktop/Synoptic" >> /home/vagrant/.bashrc
      printf "\n echo *****Commandline Interface for Synoptic*****" >> /home/vagrant/.bashrc
      
      # Remove extra applications from the launcher
      sudo rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
      sudo rm -f "/usr/share/applications/libreoffice-calc.desktop"
      sudo rm -f "/usr/share/applications/libreoffice-writer.desktop"
      sudo rm -f "/usr/share/applications/libreoffice-impress.desktop"
      sudo rm -f "/usr/share/applications/ubuntu-software-center.desktop"
      sudo rm -f "/usr/share/applications/unity-control-center.desktop"
      sudo rm -f "/usr/share/applications/ubiquity.desktop"
     
      #Reboot the system to view changes
      sudo reboot

  SHELL
end

